sudo: required
services:
- docker

before_install:
  - docker build -t ahammoudeh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahammoudeh/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t ahammoudeh/multi-client ./client
  - docker build -t ahammoudeh/multi-server ./server
  - docker build -t ahammoudeh/multi-worker ./worker
  - docker build -t ahammoudeh/multi-nginx ./nginx
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them ro docker hub
  - docker push ahammoudeh/multi-client
  - docker push ahammoudeh/multi-server
  - docker push ahammoudeh/multi-worker
  - docker push ahammoudeh/multi-nginx
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-us-east-2-973273474155
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
      secure: $AWS_SECRET_KEY